travis:
  secure:
    BINSTAR_TOKEN: pP+btx61IvRp0Gcb/+SMAXADM1YNiNa16zJfrzdbh2g20qBIPzHKpmspQbmRiQmVEe0+QZM9iWimjsvNxneMTA+tAc2wx7WMwxeaAyhSzTEO13DqSqF4uyg95rnvSEFsFjeX6IgJaxd/H2RE3eC+LSuCAEk1DAy3vExTppcsG2g5bPwMgzl1JApNLvZAA/ca1dgvNxxG6BBorf1NAB9qGRalypEcQaLoXbZWo7qdNTON07IQuNI/lnI6l+42v5xIo4e8slUWM68DOhDGT2I33mIEZcOwCEiWsSbnP5fd9oZ9wEgc7WPU6ZHSZBirxxRak5YPWeBrrCB3fuvpxUZzTLx0cBHmqldo4SdFmUBORi4jHpwHAPx0tYNj9XCAzpnBuvXlb5v7a/vbrCK5Wxkku2fPIHUvdPJ52wquRbCRbpoQtH+tGncLNr7IrlG5BDNUlmmdu9ZMnBxCVy1MegB9mwe/E4wo0AYE+XoUL3B/GueVcIt7BZ9TPTzUEwu5Fh/BzrSQK9tsWXxQHo6dXQYmQcr4K0jCK2GJ8YlOriPfwQ20/twmNLtxhbSdmvwYCm52n5Wg59o8ZLkbbMbjVSiTyx7zeCuc0jSdbtaN2LCmX49WRtCs9I50ahvGT67LdQjB1yBiHQvPOo+KoAb0oYO9xjwBf0U6HZ5J0QuiesnocK4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
