travis:
  secure:
    BINSTAR_TOKEN: HFFyb0HuXnYPP2CHGxa8IoIuRCh3d7xuErNHTwlapS++r2dpt08W+y3gBqx1/JfztbyqP72JZwYqe9KSsQqb8R1t28QNU9n1NXBcX2ud2WqXn+UgIqJmVZ1qtwVhuij0pbcTUL3eizx7bUUtBR3Uk/6N8MEDd8twM3tNPxCIsvCkSkgYjELZM1I0QLS5uagW6O60ORGsFPh+OQPP8EURsEvWoT01RPL+TIbvMYFswNY5RiBcVXp/L9rAhe7bff46x+u+gxVykecJM7dom/OoGdgYBMJjknjjflrWlb8506FTmJSnE/nrl9DrqNnO0C5BY1sq+WgMX52Y3+s2IbfxpFuhyJ2BXV9/hX/f3K4GiTcYLywO2ig0XwckRjyJLNF3oBiZk/D8Ym58EGzUwSTnwfolAWlgcpZkDhNhoiVNHCfvodS8BnvjS5yflEIf1pRH83HS7Pw2GUzV7jER3suZ9VrM2Ja8sNs6VBs+S7Qlx5pTAccQA5Uy7FuXqE/ev8nn6M+WyeMazkMUzf2kpDv4mZdKDGmFJes9cvdekKj5wFW4pzB0FhzwZ3wi3py1M8T2flMyqSGO/uyq6jJwBmK3gvFCy26S4jOlzf9nNpiXl/clJscZqBTBhp9XLld3eC50/qIXbku4y4JKd8yDNozZKfTY3ENRTKTbADZWdLInoEI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
