travis:
  secure:
    BINSTAR_TOKEN: UKxzPfyXt24o1mA7je2uFjSLRxXE8UiyETtX/ScYohUXAWKLSIKda1B6ytW19OAamQrN45oBvVhIUounN0SkmG9tfv3YzTDKkLzWU68P+Aca1ZrLEyFa1efEsuIKG1ErmW9YSHYASGEpDycVFwOnf0Di0pFTPD0B9VKhH8/T+nI7/Mn7p1RxFFC+Yqol7jQJqIW+YW34cxLeUNXi5eRPH7TwESmi4u3m+YWmsanFFUtm8BbXnX1JT1ZMsVKidhLXV/5V1HTeGgB6EuNqFQbUrr2Ym9LHpn0f350UGcuKJWUDMRCSLItv3oeJ/48AS9FcKfEV7Z8+N2LczSWOFutK+GLAN7rfF0Grznme0T/K+3JUums8m9V2CaL5MBj1ZtnkmiueM16ao/qkA17qXuMjF/TrSKL46MtKNzgNoTAcFl81ufuxyMrzPh0JxvwFgzzqL8J4upfBvDzbgmzjn1sCi1cKmfH2AlHF/SEl0+zjh+IUIeEdS2ECj/WHhpOQpDMNtjEOm8qFHzK/Umrs2Korj+hn12AFWxxFxkfGnuQ/fxMxzd2PyKDduUv/TAzNGsqVxq16Xa4DbvX2T5H76e1MiAyzcl0qn7mtrIs0vpjLxFjJPVRk89qsH4JGB7zPYBIBGABbyipkdWDC8X1ecLCrvxHW3Z5pVMaUUpNgTllHlMo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
